server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        # Evidencia de paso por gateway
        - AddResponseHeader=X-Gateway, OK
      routes:
        # ==== Ruta principal hacia tu SwipeService ====
        - id: swipe-service
          uri: lb://SWIPE-SERVICE   # usa Eureka. Sin Eureka: ver application-local.yml más abajo
          predicates:
            - Path=/swipe-service/**
          filters:
            - StripPrefix=1
            # Si tus endpoints internos no cuelgan de /api/** o requieren otra raíz, descomenta:
            # - RewritePath=/swipe-service/(?<segment>.*), /${segment}

        # ==== Swagger / OpenAPI del backend expuesto via gateway ====
        - id: swipe-service-openapi
          uri: lb://SWIPE-SERVICE
          predicates:
            - Path=/swipe-service/v3/api-docs/**,/swipe-service/swagger-ui.html,/swipe-service/swagger-ui/**,/swipe-service/webjars/**,/swipe-service/swagger-resources/**
          filters:
            - StripPrefix=1

      # CORS global para orígenes de desarrollo
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://127.0.0.1:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka

# El Swagger UI que sirve el gateway muestra la API del SwipeService (proxied)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    urls:
      - name: SwipeService
        url: /swipe-service/v3/api-docs
    disable-swagger-default-url: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,httpexchanges
  endpoint:
    health:
      show-details: always
